### PR TITLE
0.9.5 Release.

### PR DESCRIPTION
**Pull request by EBatTiVo**
<ul>
    <li>Add new typing support for type checking and completion. (Thanks to Carlos Ballesteros!) (Issues #288,#291,#308,#317)</li>
    <li>Support static extensions in completion. (Again, Thanks, Carlos!)<li>
    <li>Fix debugger getting stuck "collecting data" for some variables (particularly, "this"). (Issue #325)</li>
    <li>Better compiler error highlighting. (Issue #180 redux.)</li>
    <li>Fix Cut/Copy/Paste buffer inconsistencies (Issue #196)</li>
    <li>Add generics support. (First level only, chained sequences remain incomplete.)</li>
    <li>Allow object literals as return statements. (Issue #278)</li>
    <li>Fix NPE during annotation, causing annotation to stop. (Issue #316)</li>
  </ul>

### CODE REVIEW

**Comment by EBatTiVo** [comment]
This pull request has been sitting long enough that we're up to release 0.9.7 now.

**Comment by as3boyan** [comment]
Merge?

**Comment by EBatTiVo** [comment]
Boyan, Good to see you back on-line!

> Merge?

I would say yes, but since nobody can open project structures, I guess we should wait until I fix that.  I'm back at work today, so maybe in a couple of days.

**Comment by as3boyan** [comment]
It is great to see that you guys still working on this project. JetBrains release new versions so fast, it is hard to match

**Pull request closed without merging**
